name: VanishX
main: Luthfi\VanishX\VanishX
version: 1.1.0
api: 5.0.0
author: Luthfi
description: A plugin that allow players to vanish.
website: https://github.com/LuthMC/VanishX

permissions:
  vanishx.use:
    default: op
    description: Allow player to use the /vanish command.
    
  vanishx.other:
    default: op
    description: Allow player to receive notifications when players vanish.

  vanishx.break:
    default: op
    description: Allow player to breaking blocks while vanished.
